### ISSUE TITLE
Checkin/Checkout System

### ISSUE THREAD

**Issue by amaredeus** [BanklessDAO/DEGEN#79]
Dev guild came to the conclusion of remunerating contributors at about 1000 BANK/hr. This may or may not expand and might be removed altogether. 

/checkin
/checkout

simply stores user, startDate, endDate in db

NOT YET FINALIZED

**Comment by nonsensecodes** [comment]
This has potential.

`/checkin` to "clock in," `/checkout` to "clock out," and perhaps `/hours` to view total hours worked. We'll need to set up filters to accommodate for hours worked per week, month, and season. We'll need to establish a system to verify as well.
